environments:
  infra:
    values:
      - env: "infra"
      - rootPath: "../helmfile"

bases:
  - releases/haproxy.yaml
  - releases/cert-manager.yaml
  - releases/cert-manager-issuers.yaml
  - releases/dashboard.yaml