repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: infra
    chart: jetstack/cert-manager
    version: ~v1.10.1
    values:
      - values/infra/cert-manager.yaml