repositories:
  - name: nginx-ingress
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx-ingress
    namespace: infra
    chart: ingress-nginx/ingress-nginx
    version: 4.4.0
    values:
      - values/infra/nginx.yaml